name: Fix PHP code style issues

on: push

jobs:
    php-code-styling:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              with:
                  ref: ${{ github.head_ref }}

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.2'
                  coverage: none

            - name: Install composer dependencies
              run: composer install -n --prefer-dist

            - name: Fix PHP code style issues
              run: composer lint

            - name: Commit changes
              uses: stefanzweifel/git-auto-commit-action@v5
              with:
                  commit_message: Fix styling
